### PR TITLE
Update ransomware_gang.md for new Stormous domains

### PR DESCRIPTION
**Pull request by cocaman**

### CODE REVIEW

**Comment by ErezDasa** [comment]
This new sites doesn't looks like Stormous sites.....

**Comment by cocaman** [comment]
pdcizqzjitsgfcgqeyhuee5u6uki6zy5slzioinlhx6xjnsw25irdgqd was mentioned as their new site on their Telegram on 2023-12-18, and from there they link to the other .onion domain where they announced to post files of the impacted organization.

**Comment by ErezDasa** [comment]
OK, it's slightly weird but thanks for the info.

**Comment by cocaman** [comment]
also this
screenshot

**Comment by fastfire** [comment]
Thank you @cocaman

**Pull request merged**
